export const UPDATE_FILE_CONTENT = 'UPDATE_FILE_CONTENT';
export const UPDATE_FILE_NAME = 'UPDATE_FILE_NAME';
export const DELETE_FILE = 'DELETE_FILE';
export const CREATE_FILE = 'CREATE_FILE';
export const SET_SELECTED_FILE = 'SET_SELECTED_FILE';
